# Generated by Django 5.2.3 on 2025-06-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_order_community_alter_order_mamamboga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='community',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mamamboga',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receiver',
        ),
    ]
