# Generated by Django 5.2.3 on 2025-06-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_created_by_and_more'),
        ('payments', '0004_remove_payment_order'),
        ('stock', '0005_alter_product_product_price'),
        ('users', '0002_rename_mamamboga_name_mamamboga_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='community',
            field=models.ForeignKey(default='Community A', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='communities.community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='mamamboga',
            field=models.ForeignKey(default='Mama Mwangi', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.mamamboga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='Carrots', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stock.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default='Carrot', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='receiver',
            field=models.ForeignKey(default='Taimba', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.stakeholder'),
            preserve_default=False,
        ),
    ]
