<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-25 16:36
=======

>>>>>>> 91d623c5f021582307144920b7713b6d7c89832a

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mamamboga',
            old_name='mamamboga_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='mamamboga',
            old_name='mamamboga_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='stakeholder_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='stakeholder_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='mamamboga',
            name='last_name',
<<<<<<< HEAD
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
=======
            field=models.CharField(default='unknown', max_length=50),
>>>>>>> 91d623c5f021582307144920b7713b6d7c89832a
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
