# Generated by Django 5.2.3 on 2025-06-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_stakeholder_mamamboga_certified_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamamboga',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
