# Generated by Django 5.2.3 on 2025-06-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_mamamboga_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamamboga',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
