# Generated by Django 5.2.3 on 2025-06-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communitymembers',
            name='membership_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainingregistration',
            name='registration_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainingsessions',
            name='session_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
