# Generated by Django 5.2.3 on 2025-06-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
