# Generated by Django 5.2.3 on 2025-06-27 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('users', '0004_alter_mamamboga_id_alter_stakeholder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='mamamboga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='users.mamamboga'),
        ),
    ]
