# Generated by Django 5.2.3 on 2025-06-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_mamamboga_delete_mamamboga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='mamamboga',
        ),
    ]
